# Generated by Django 3.2.5 on 2021-07-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Ticker', models.CharField(max_length=20)),
                ('Exchange', models.CharField(max_length=150)),
                ('Sentiment_Today', models.IntegerField(blank=True, null=True)),
                ('Mentions_Today', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
